typography_spectrum: 0.5629148265401289
content_rating:
  adult: false
color:
  brandStrength: 0.9534175580943759
  lightness: 0.6221388966539451
  saturation: 0.9932664215086157
  rhythmicContrast: 0.2825753356184405
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
github: true
layout_spectrum: 0.8948036461184262
author:
  name: Tony Richie
  email: tony@tonyrichie.com
  url: 'http://www.tonyrichie.com'
name: Tony Richie
navigation:
  - name: Cars
    id: 7b8b6f53-4062-4a05-815b-1030c1c5e854
    type: content
title: 'To Inspire, Educate and Empower!'
content: []
description: >-
  This is my daily life as a new economy digital entrepreneur. Follow me and
  learn how to live the good life by using todays trends and technologies. 
purpose:
  - type: contact
    url: 'mailto:tony@tonyrichie.com'
    label: Contact me
  - type: contact
    url: 'tel:1-800-683-1726'
    label: Call 1-800-683-1726
