layout_spectrum: 0.40629887536011344
typography_spectrum: 0.5164927816994968
color:
  brandStrength: 0.5257964740173504
  lightness: 0.506262657036636
  saturation: 0.5136059777796416
  rhythmicContrast: 0.5949895524061146
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
content_rating:
  adult: false
github: true
author:
  name: Tony Richie
  email: tony@tonyrichie.com
  url: 'http://www.tonyrichie.com'
name: Tony Richie
navigation:
  - name: Cars
    id: 7b8b6f53-4062-4a05-815b-1030c1c5e854
    type: content
  - name: About me
    id: 6f59b115-69e5-44d0-af32-25d0b317b116
    type: content
title: 'To Inspire, Educate and Empower!'
content: []
description: >-
  This is my daily life as a new economy digital entrepreneur. Follow me and
  learn how to live the good life by using todays trends and technologies. 
purpose:
  - type: contact
    url: 'mailto:tony@tonyrichie.com'
    label: Contact me
  - type: contact
    url: 'tel:1-800-683-1726'
    label: Call 1-800-683-1726
